"""Packet River scoring service.

Owns the flags (generated by flags.py at boot), the accounts, the runs, and the
leaderboard. The only way to score is to submit a real flag string that exists
only inside the vulnerable resource it was planted in; there is no
"award points" endpoint. On a valid submission it publishes pkt/score/events so
simmap breaks that part of the town.
"""
from __future__ import annotations

import hmac
import json
import os
import pathlib
import re
import sqlite3
import time

import paho.mqtt.client as mqtt
from flask import Flask, g, jsonify, request

import auth
import flags as flagmod
from score import compute

DB_PATH = pathlib.Path("/data/scoring.db")
SCHEMA = pathlib.Path(__file__).with_name("schema.sql")
MQTT_HOST = os.environ.get("MQTT_HOST", "bus")
MQTT_PORT = int(os.environ.get("MQTT_PORT", "1883"))

NAME_RE = re.compile(r"^[A-Za-z0-9_.-]{3,20}$")

app = Flask(__name__)
_alert_level = 0
_mqtt: mqtt.Client | None = None


# -- infra -----------------------------------------------------------------
def db() -> sqlite3.Connection:
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH)
        g.db.row_factory = sqlite3.Row
        g.db.execute("PRAGMA foreign_keys = ON")
    return g.db


@app.teardown_appcontext
def _close_db(_exc):
    d = g.pop("db", None)
    if d is not None:
        d.close()


def init_db() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.executescript(SCHEMA.read_text())
    conn.commit()
    conn.close()


def mqtt_connect() -> None:
    global _mqtt
    _mqtt = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id="scoring")
    if os.environ.get("MQTT_USER"):
        _mqtt.username_pw_set(os.environ["MQTT_USER"], os.environ.get("MQTT_PASS", ""))

    def on_connect(c, u, flags_, rc, props):
        c.subscribe("pkt/alert/level")
        c.subscribe("pkt/creds/rotate")

    def on_message(c, u, msg):
        global _alert_level
        if msg.topic == "pkt/creds/rotate":
            try:
                import creds
                creds.generate()
                c.publish("pkt/creds/changed", "{}")
            except Exception as exc:
                print("[scoring] cred rotate:", exc)
            return
        try:
            _alert_level = int(json.loads(msg.payload.decode() or "{}").get("level", 0))
        except Exception:
            pass

    _mqtt.on_connect = on_connect
    _mqtt.on_message = on_message
    for _ in range(30):
        try:
            _mqtt.connect(MQTT_HOST, MQTT_PORT, keepalive=30)
            break
        except OSError:
            time.sleep(2)
    _mqtt.loop_start()


def publish(topic: str, payload: dict) -> None:
    if _mqtt is not None:
        _mqtt.publish(topic, json.dumps(payload))


def current_user() -> dict | None:
    return auth.read_session(request.headers.get("Cookie"))


def active_run(user_id: int) -> sqlite3.Row | None:
    return db().execute(
        "SELECT * FROM runs WHERE user_id=? ORDER BY id DESC LIMIT 1", (user_id,)
    ).fetchone()


def run_total(run_id: int) -> int:
    r = db().execute(
        "SELECT COALESCE(SUM(points),0) AS t FROM submissions WHERE run_id=?", (run_id,)
    ).fetchone()
    return int(r["t"])


# -- health + config -----------------------------------------------------
@app.get("/health")
def health():
    return {"ok": True}


# -- accounts ----------------------------------------------------------
@app.post("/api/score/register")
def register():
    data = request.get_json(force=True, silent=True) or {}
    name = (data.get("name") or "").strip()
    pw = data.get("password") or ""
    if not NAME_RE.match(name):
        return {"error": "name must be 3-20 chars, letters/digits/._-"}, 400
    if len(pw) < 6:
        return {"error": "password must be at least 6 characters"}, 400
    try:
        cur = db().execute(
            "INSERT INTO users (name, pw_hash) VALUES (?,?)",
            (name, auth.hash_password(pw)),
        )
        db().execute("INSERT INTO scores (user_id) VALUES (?)", (cur.lastrowid,))
        db().commit()
    except sqlite3.IntegrityError:
        return {"error": "that name is taken"}, 409
    resp = jsonify({"name": name})
    resp.headers["Set-Cookie"] = auth.make_cookie(cur.lastrowid, name)
    return resp


@app.post("/api/score/login")
def login():
    data = request.get_json(force=True, silent=True) or {}
    name = (data.get("name") or "").strip()
    pw = data.get("password") or ""
    row = db().execute("SELECT * FROM users WHERE name=?", (name,)).fetchone()
    if not row or not auth.verify_password(pw, row["pw_hash"]):
        return {"error": "wrong name or password"}, 401
    resp = jsonify({"name": name})
    resp.headers["Set-Cookie"] = auth.make_cookie(row["id"], name)
    return resp


@app.post("/api/score/logout")
def logout():
    resp = jsonify({"ok": True})
    resp.headers["Set-Cookie"] = auth.clear_cookie()
    return resp


@app.get("/api/score/me")
def me():
    u = current_user()
    if not u:
        return {"anon": True, "alert_level": _alert_level}
    s = db().execute(
        "SELECT total, best_run_total FROM scores WHERE user_id=?", (u["uid"],)
    ).fetchone()
    run = active_run(u["uid"])
    return {
        "name": u["name"],
        "total": s["total"] if s else 0,
        "best": s["best_run_total"] if s else 0,
        "alert_level": _alert_level,
        "active_run": {"id": run["id"], "score_so_far": run_total(run["id"])} if run else None,
    }


# -- runs + scoring --------------------------------------------------
@app.post("/api/score/run")
def start_run():
    u = current_user()
    if not u:
        return {"error": "log in first"}, 401
    cur = db().execute(
        "INSERT INTO runs (user_id, started_ts) VALUES (?,?)", (u["uid"], time.time())
    )
    db().commit()
    return {"run_id": cur.lastrowid}


@app.post("/api/score/arm")
def arm():
    u = current_user()
    if not u:
        return {"error": "log in first"}, 401
    tid = (request.get_json(force=True, silent=True) or {}).get("technique_id", "")
    run = active_run(u["uid"])
    if not run:
        return {"error": "start a run first"}, 409
    if not db().execute("SELECT 1 FROM flags WHERE technique_id=?", (tid,)).fetchone():
        return {"error": "unknown technique"}, 404
    db().execute(
        "INSERT OR REPLACE INTO armed (run_id, technique_id, armed_at, alert_at_arm) "
        "VALUES (?,?,?,?)",
        (run["id"], tid, time.time(), _alert_level),
    )
    db().commit()
    return {"armed": True, "technique_id": tid}


@app.post("/api/score/submit")
def submit():
    u = current_user()
    if not u:
        return {"error": "log in first"}, 401
    flag = ((request.get_json(force=True, silent=True) or {}).get("flag") or "").strip()
    run = active_run(u["uid"])
    if not run:
        return {"error": "start a run first"}, 409

    match = None
    for row in db().execute("SELECT * FROM flags").fetchall():
        if hmac.compare_digest(flag, row["flag"]):
            match = row
            break
    if not match:
        publish("pkt/score/events", {"type": "reject", "user": u["name"]})
        return {"accepted": False}

    dup = db().execute(
        "SELECT 1 FROM submissions WHERE run_id=? AND technique_id=?",
        (run["id"], match["technique_id"]),
    ).fetchone()
    if dup:
        return {"accepted": False, "detail": "already claimed this run"}

    armed = db().execute(
        "SELECT armed_at, alert_at_arm FROM armed WHERE run_id=? AND technique_id=?",
        (run["id"], match["technique_id"]),
    ).fetchone()
    started = armed["armed_at"] if armed else run["started_ts"]
    alert_at_arm = armed["alert_at_arm"] if armed else _alert_level
    elapsed = max(0.0, time.time() - started)

    prior = db().execute(
        "SELECT COUNT(DISTINCT s.technique_id) AS n FROM submissions s "
        "JOIN flags f ON f.technique_id = s.technique_id "
        "WHERE s.run_id=? AND f.subsystem=?",
        (run["id"], match["subsystem"]),
    ).fetchone()["n"]

    points, breakdown = compute(match["base"], alert_at_arm, _alert_level, prior, elapsed)

    db().execute(
        "INSERT INTO submissions "
        "(run_id, user_id, technique_id, points, stealth, chain_n, elapsed_s) "
        "VALUES (?,?,?,?,?,?,?)",
        (run["id"], u["uid"], match["technique_id"], points,
         breakdown["stealth"], prior, elapsed),
    )
    rt = run_total(run["id"])
    db().execute(
        "UPDATE scores SET total = total + ?, "
        "best_run_total = MAX(best_run_total, ?) WHERE user_id=?",
        (points, rt, u["uid"]),
    )
    db().commit()

    publish("pkt/score/events", {
        "technique_id": match["technique_id"],
        "target": match["target"],
        "shop": match["target"],
        "effect": match["effect"],
        "severity": match["severity"],
        "subsystem": match["subsystem"],
        "user": u["name"],
        "run_id": run["id"],
    })

    total = db().execute(
        "SELECT total FROM scores WHERE user_id=?", (u["uid"],)
    ).fetchone()["total"]
    return {
        "accepted": True,
        "points": points,
        "breakdown": breakdown,
        "target": match["target"],
        "run_total": rt,
        "new_total": total,
    }


@app.get("/api/score/leaderboard")
def leaderboard():
    rows = db().execute(
        "SELECT u.name, s.best_run_total, s.total "
        "FROM scores s JOIN users u ON u.id = s.user_id "
        "WHERE s.best_run_total > 0 OR s.total > 0 "
        "ORDER BY s.best_run_total DESC, s.total DESC LIMIT 25"
    ).fetchall()
    return jsonify([dict(r) for r in rows])


if __name__ == "__main__":
    init_db()
    mqtt_connect()
    app.run(host="0.0.0.0", port=8001, threaded=True)
